#
#  Author: Hari Sekhon
#  Date: 2021-06-11 11:35:45 +0100 (Fri, 11 Jun 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                    A r g o C D   K u s t o m i z a t i o n
# ============================================================================ #

# run: argocd app sync argocd --local $PWD --dry-run

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:                      # // is intentional to only copy from this path down
#- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.0.3
#
# but // causes this error in Kustomize 3.5 (the argocd-repo-server.kustomize.patch.yaml upgrades Kustomize and should fix this too):
#
#     Error: accumulating resources: accumulateFile "accumulating resources from 'github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.0.3': evalsymlink failure on '/tmp/git@repo/argocd/overlay/github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.0.3' : lstat /tmp/git@repo/argocd/overlay/github.com: no such file or directory", accumulateDirector: "recursed accumulation of path '/tmp/kustomize-881686007/repo': accumulating resources: accumulateFile \"accumulating resources from '../namespace-install': evalsymlink failure on '/tmp/kustomize-881686007/namespace-install' : lstat /tmp/kustomize-881686007/namespace-install: no such file or directory\", loader.New \"Error loading ../namespace-install with git: url lacks host: ../namespace-install, dir: evalsymlink failure on '/tmp/kustomize-881686007/namespace-install' : lstat /tmp/kustomize-881686007/namespace-install: no such file or directory, get: invalid source string: ../namespace-install\""
#
# so keep it simple, this works:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.0.3

resources:
- argocd-self.yaml  # GitOps self-management tracking of ArgoCD config itself
- argocd-ingress.yaml
- argocd-ingress-grpc.yaml
#- argocd-project.yaml
#- argocd-application.yaml
#- clusters-secrets.yaml
#- repos-secrets.yaml

# XXX: don't define namespace in these patches, will break patching, see argocd-cm.patch.yaml for details why
patchesStrategicMerge:
# General ArgoCD Settings:
#
- argocd-cm.patch.yaml
#
# Kustomize - download specific version:
#
#- argocd-repo-server.kustomize.patch.yaml
#
# Azure AD SSO patches:
#
#- argocd-cm.azure-ad.patch.yaml
#- argocd-rbac-cm.patch.yaml
#- argocd-cm.disable-admin.patch.yaml

#patchesJson6902:
#- target:
#    version: v1
#    group: apps
#    kind: Deployment
#    name: argocd-server
#    namespace: argocd
#  path: argocd-server.http.patch.yaml
