#
#  Author: Hari Sekhon
#  Date: 2021-06-10 18:26:29 +0100 (Thu, 10 Jun 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  # XXX: Edit
  name: NAME
  namespace: argocd  # must be the namespace where ArgoCD was installed - usually 'argocd'
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
	# XXX: Edit
  description: DESCRIPTION
  # Allow manifests to deploy from any Git repos

  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster

  destinations:
	# XXX: Edit
  - namespace: NAMESPACE
  # XXX: Edit - this is fine for in-cluster deployments, otherwise give external Master URL for deployments to other clusters
    server: https://kubernetes.default.svc

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet

  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to NAME  # XXX: Edit
    policies:
    - p, proj:my-project:read-only, applications, get, NAME/*, allow  # XXX: Edit
    groups:
		# XXX: Edit
    - my-oidc-group

  # A role which provides sync privileges to only the guestbook-dev application, e.g. to provide
  # sync privileges to a CI system
  - name: ci-role
    description: Sync privileges for guestbook-dev
    policies:
		# XXX: Edit
    - p, proj:my-project:ci-role, applications, sync, NAME/APP, allow
    # NOTE: JWT tokens can only be generated by the API server and the token is not persisted
    # anywhere by Argo CD. It can be prematurely revoked by removing the entry from this list.
    jwtTokens:
    - iat: 1535390316
