#
#  Author: Hari Sekhon
#  Date: 2021-06-09 15:49:46 +0100 (Wed, 09 Jun 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ArgoCD - disable the default admin user after SSO integration eg. to Azure Active Directory
#
#   https://argoproj.github.io/argo-cd/operator-manual/user-management/

# Check it's disabled via:
#
#   argocd account get --account admin

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "false"
