#
#  Author: Hari Sekhon
#  Date: 2021-06-11 11:35:45 +0100 (Fri, 11 Jun 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                    A r g o C D   K u s t o m i z a t i o n
# ============================================================================ #

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:                     # // is intentional to only copy from this path down
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.0.3

resources:
- argocd-ingress.yaml
- argocd-ingress-grpc.yaml
#- argocd-project.yaml
#- argocd-application.yaml
#- clusters-secrets.yaml
#- repos-secrets.yaml

patchesStrategicMerge:
- argocd-cm.patch.yaml
# Azure AD SSO
#- argocd-cm.azure-ad.patch.yaml
#- argocd-rbac-cm.patch.yaml
#- argocd-cm.disable-admin.patch.yaml

#patchesJson6902:
#- target:
#    version: v1
#    group: apps
#    kind: Deployment
#    name: argocd-server
#    namespace: argocd
#  path: argocd-server.http.patch.yaml
