#
#  Author: Hari Sekhon
#  Date: 2022-08-24 16:35:39 +0100 (Wed, 24 Aug 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                      G i t   A s k P a s s   S c r i p t
# ============================================================================ #

# simplified version of https://github.com/HariSekhon/DevOps-Bash-tools/blob/master/git_askpass.sh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: git-askpass
  #namespace: NAMESPACE  # override this in kustomization.yaml, eg. see argocd-kustomization.yaml
data:
  git_askpass.sh: |
    #!/usr/bin/env bash
    set -euo pipefail
    echo "username=${GIT_USERNAME:-${GIT_USER:-}}"
    echo "password=${GIT_TOKEN:-${GIT_PASSWORD:-}}"
