#
#  Author: Hari Sekhon
#  Date: 2021-02-23 12:53:33 +0000 (Tue, 23 Feb 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                          J e n k i n s   C I   P o d
# ============================================================================ #

# see Jenkinsfile template referencing this pod template:
#
#   https://github.com/HariSekhon/Templates/blob/master/Jenkinsfile

---
apiVersion: v1
kind: Pod
metadata:
namespace: jenkins
#  labels:
#  app: gcloud-sdk
spec:
  priorityClassName: high-priority  # requires priorityclass.yaml
  affinity:
    # avoid preemption which can cause build failures
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-preemptible
            operator: DoesNotExist
          - key: eks.amazonaws.com/capacityType
            operator: NotIn
            values:
            - SPOT
          - key: kubernetes.azure.com/scalesetpriority
            operator: NotIn
            values:
            - spot
  containers:
  - name: gcloud-sdk  # do not name this 'jnlp', without that container this'll never come up properly to execute the build
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    # works without this
    #command:
    #- cat
    tty: true
    resources:
      requests:
        cpu: 300m  # actually takes 800m but overcontend rather than spawning too many nodes for bursty workload
        memory: 300Mi # uses around 250Mi
      limits:
        cpu: "1"
        memory: 1Gi
    # more containers if you want to run different stages in different containers
#  - name: busybox
#    image: busybox
#    command:
#    - cat
#    tty: true
#  - name: golang
#    image: golang:1.10
#    command:
#    - cat
#    tty: true
