#
#  Author: Hari Sekhon
#  Date: 2021-02-23 13:33:31 +0000 (Tue, 23 Feb 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                      J e n k i n s   C I   -   A g e n t
# ============================================================================ #

# StatefulSet to maintain a predictable pool of Jenkins Agents online to avoid spin-up delay

# This is much more complicated than just using the Jenkins Kubernetes plugin which should be preferred

# See Instead:
#
#   jenkins-cloud-pod.yaml - for Jenkins Kubernetes plugin (burstable)
#
#   https://hub.docker.com/r/jenkins/inbound-agent/

# If you only want 1 Jenkins agent, you can simply set JENKINS_SECRET under env, but if you want multiple agents you need to use some external Secret injection, eg.

# - GCP Secret Manager integration:
#   - Requirements:
#     - jenkins-agent K8s service account annotated with jenkins-agent GCP service account (see jenkins-agent-serviceaccount.yaml)
#     - jenkins-agent GCP service account
#     - serviceAccount:PROJECT_ID.svc.id.goog[K8S_NAMESPACE/KSA_NAME] must be granted to use jenkins-agent GCP service account
#     - Secret Manager API must be enabled in project
#     - create the Nodes in Jenkins Server: jenkins-agent-0, jenkins-agent-1, jenkins-agent-2
#     - copy the secret tokens from Jenkins Server to GCP Secret Manager as: jenkins-agent-0-token, jenkins-agent-1-token and jenkins-agent-2-token

---
apiVersion: apps/v1
kind: StatefulSet  # for predictable names and to align to individual connection secrets
metadata:
  name: jenkins-agent
  namespace: jenkins
  labels:
    app: jenkins-agent
spec:
  replicas: 3
  serviceName: jenkins-agent
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      priorityClassName: high-priority
      affinity:
        # avoid GKE preemption causing build failures
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-preemptible
                  operator: DoesNotExist
#          preferredDuringSchedulingIgnoredDuringExecution:
#            - weight: 100
#              preference:
#                matchExpressions:
#                  - key: cloud.google.com/gke-preemptible
#                    operator: DoesNotExist
      tolerations:
        - key: cloud.google.com/gke-preemptible
          operator: Equal
          value: "false"
          effect: PreferNoSchedule
      serviceAccountName: jenkins-agent
      # XXX: Trick: dynamically get the jenkins agent secret from GCP Secret Manager, populate to a file to be picked up by main container as a form of late evaluation since we can't use downwards API to populate different K8s secrets
      # WARNING: only do this in very trusted environments or an isolated project - if Devs or untrusted users can run code in your Jenkins Agents via build jobs then they can read out the Secret Manager secrets for the current project!
      #          Consider using the jenkins-cloud-pod.yaml for Kubernetes plugin instead to dynamically spin up agents
      #          Other options are run a separate stateful for each agent or put all agent secrets in the env and have the initContainer load the one matching the current hostname
      initContainers:
        - name: gcp-secret-mount
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            # find latest version of the JENKINS_SECRET in GCP Secret Manager secret called 'jenkins-agent-N-token' and download it to /secrets/token to be picked up by the main jenkins-agent container
            # Workload Identity - auth for this is done by linking k8s service account to external GCP service account which must be granted GCP IAM permission to read secrets from GCP Secret Manager
            # this requires GCP jenkins-agent@$PROJECT_ID.iam.gserviceaccount.com (bound by jenkins-agent k8s serviceaccount above) to be granted IAM roles:
            #
            #   Secret Manager Secret Accessor
            #   Secret Manager Secret Version Manager  # to list the latest secret version
            #
            - gcloud secrets versions access $(gcloud secrets versions list "${JENKINS_AGENT_NAME}-token" --filter='state=enabled' --format='value(name)' | sort -k1nr | head -n1) --secret="${JENKINS_AGENT_NAME}-token" > /secret/token
          env:
            - name: CLOUDSDK_CORE_PROJECT
              # XXX: set PROJECT_ID to your GCP project containing your Secrets Manager secrets: jenkins-agent-N-token
              value: PROJECT_ID
            - name: JENKINS_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: secret
              mountPath: /secret
              readOnly: false
      containers:
      - name: jenkins-agent
        # there is no lts tag at this time
        #image: jenkins/inbound-agent:latest
        #image: jenkins/inbound-agent:4.6-1
        image: harisekhon/jenkins-agent-docker:4.6
        imagePullPolicy: IfNotPresent
        command:
          # use shell in order to late eval contents of /secret/token into an arg
          - sh
        args:
          - -c
          # not feeding as args that that behaviour is much more buggy and dependent on entrypoint positional arg parsing which doesn't work as documented
          - "JENKINS_SECRET=$(cat /secret/token; rm -f /secret/token) jenkins-agent"
        ports:
          - name: agent
            containerPort: 50001
        #securityContext:
        #  privileged: true
        env:
          - name: JENKINS_AGENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          # JENKINS_NAME for legacy support
          #- name: JENKINS_NAME
          #  value: $(JENKINS_AGENT_NAME)
          - name: JENKINS_URL
            value: http://jenkins-ui.jenkins.svc.cluster.local:8080
          - name: JENKINS_TUNNEL
            value: jenkins-discovery.jenkins.svc.cluster.local:50000
#          - name: JENKINS_SECRET
#            valueFrom:
#              secretKeyRef:
#                # doesn't interpolate
#                #name: $(JENKINS_AGENT_NAME)-secret
#                #key: $(JENKINS_AGENT_NAME)-secret
#                # You can do this if you only want 1 agent, but if you want multiple you need to read the notes near the top
#                name: jenkins-agent-0-secret
#                key: jenkins-agent-0-secret
          - name: JENKINS_AGENT_WORKDIR
            # XXX: this path should match the Jenkins Server "Remote root directory" config option
            value: /var/jenkins
        resources:
          limits:
            cpu: 4
            memory: 5Gi  # GiB
          requests:
            # millicores - 1/1000 of a CPU / vCPU
            # 100m = 1/10th of CPU core
            cpu: 1
            memory: 1.5Gi  # MiB
        tty: false
        volumeMounts:
          - name: workspace
            # XXX: this path should match the Jenkins Server "Remote root directory" config option
            mountPath: /var/jenkins
            readOnly: false
          - name: secret
            mountPath: /secret
            readOnly: false
        workingDir: /var/jenkins
      volumes:
        - name: workspace
          emptyDir: {}
        - name: secret
          emptyDir: {}
