#
#  Author: Hari Sekhon
#  Date: 2021-02-22 15:10:07 +0000 (Mon, 22 Feb 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                   J e n k i n s   K u s t o m i z a t i o n
# ============================================================================ #

# Ties all the Jenkins resources together for an easy one-shot deployment

# Quick Reference:
#
# https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html
#
# https://kubectl.docs.kubernetes.io/pages/examples/kustomize.html
#
# https://github.com/HariSekhon/Kubernetes-templates/blob/master/kustomization.yaml

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins

# if deploying to multiple environments
#namePrefix: dev-

resources:
  - ./storageclass-gcp-standard-resizeable.yaml
  - ./jenkins-namespace.yaml
  #- ./jenkins-agent.yaml
  - ./jenkins-agent-serviceaccount.yaml
  - ./jenkins-ingress.yaml
  - ./jenkins-server-role.yaml
  - ./jenkins-server-rolebinding.yaml
  - ./jenkins-server-serviceaccount.yaml
  - ./jenkins-server.yaml
  - ./jenkins-service-discovery.yaml
  - ./jenkins-service-ui.yaml
