#
#  Author: Hari Sekhon
#  Date: 2020-09-21 13:19:44 +0100 (Mon, 21 Sep 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                               K u s t o m i z e
# ============================================================================ #

# Quick Reference:
#
# https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html
#
# https://kubectl.docs.kubernetes.io/pages/examples/kustomize.html

# =============

# Edit / Delete below as necessary for your environment (it's easier than remembering / finding / adding all this stuff)

# =============

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# override namespace for all resources
# may cause duplicate namespace clashes if different namespaces are defined in bases
namespace: NAMESPACE

# add resource configs from ../../base/kustomization.yaml
#bases:
#- ../../base

#namePrefix: dev-

# set labels on all resources and selectors - will override base
# eg. this will replace all 'app' labels
commonLabels:
  app: NAME-dev

# set annotations on all resources - will override base
#commonAnnotations:
#  annotationKey1: annotationValue2

# ========================

resources:
- namespace.yaml
- deployment.yaml
- statefulset.yaml
- service.yaml
#- cronjob.yaml
#- github.com/username/repo # can add paths and ?ref=dev-branch or ?ref=v1.0.6

# ========================
# Strategic Merge Patching
#
# must name metadata.name [and often metadata.namespace] in order to match exact resources from the above yamls to match + patch
patchesStrategicMerge:
  # overrides replica counts / memory / ports across environments etc - anything that could be defined in a normal deployment
#- deployment.patch.yaml

  # set in cronjob.yml now - besides this is too generic without metadata.name necessary for patching selection, designed to be called from CLI as a fix
#- cronjob-fix-stale.patch.yaml

  # enable to override LoadBalancer to NodePort for testing locally
#- service-nodeport.patch.yaml

  # quick fix temporary init container to reset things like mount point permissions / owner mismatch - a common problem, easily solved this way
#- init-container-fix.patch.yaml

# =====================
# Multi-Object Patching
#
#   patch multiple objects at once - make the patch generic and target it in kustomization.yaml
#
#   https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md
#
patches:
#- path: somepatch.yaml  # can be the same as a strategic merge patch but with metadata.name set to any value as it's ignored
#  target:
#    group: <optional group>
#    version: <optional version>
#    kind: <optional kind>
#    name: <optional name>
#    namespace: <optional namespace>
#    labelSelector: <optional label selector>
#    annotationSelector: <optional annotation selector>

  # make cronjobs preemptible if this kustomization is used on dev/staging environments
- path: cronjob-preemptible.patch.yaml
  target:
    kind: CronJob

  # apply the same firewall and tuning to all Ingresses without duplicating lots of config
- path: ./ingress.nginx.patch.yaml
  target:
    kind: Ingress
    annotationSelector: kubernetes.io/ingress.class=nginx

# =============
# JSON Patching - not my favourite way of doing it, prefer patchesStrategicMerge above
#                 the only reason to use this is because not all resources or fields support strategic merge patches, or if you need to add to an array
#
#   https://github.com/kubernetes-sigs/kustomize/blob/master/examples/jsonpatch.md
#   https://tools.ietf.org/html/rfc6902
#
#patchesJson6902:
#- target:
#    version: v1
#    kind: Deployment
#    name: NAME
#  path: some.patch.yaml
#  # OR inline
#  patch: |-
#    - op: replace
#      path: /some/existing/path
#      value: new value

# XXX: Danger - this breaks all existing normal ingress terminated SSL services
#patchesJson6902:
#- target:
#    version: v1
#    group: apps
#    kind: Deployment
#    name: ingress-nginx-controller
#    namespace: ingress-nginx
#  path: nginx-ingress.passthrough.patch.yaml


# =======================
# Images + Tags overrides
#
#   can use newName and/or newTag
#
images:
- name: eu.gcr.io/myproject/myimage
  newName: eu.gcr.io/myproject/myotherimage
  newTag: "latest"

# =======================

configMapGenerator:
# useful for straight mounts to files
#- name: my-config-files
#  files:
#    - file1.properties
#    - file2.properties
# useful for extracting to environment variables
- name: my-env
  namespace: NAMESPACE
  literals:
  - env=dev
  - version=latest
