#
#  Author: Hari Sekhon
#  Date: 2022-05-12 16:54:07 +0100 (Thu, 12 May 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                                  D a t r e e
# ============================================================================ #

# Logs results to https://app.datree.io

---
name: Datree

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**.yml'
      - '**.yaml'
      - !.github/workflows/
      - .github/workflows/datree.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '*.yml'
      - '*.yaml'
      - .github/workflows/datree.yaml
  workflow_dispatch:
    inputs:
      path:
        type: string
        default: '**.y*ml'
        required: false
      # https://hub.datree.io/setup/cli-arguments
      args:
        type: string
        default: --only-k8s-files
        required: false
      isHelmChart:
        type: boolean
        required: false
      helmArguments:
        type: string
        required: false
      isKustomization:
        type: boolean
        required: false
      kustomizeArguments:
        type: string
        required: false

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  datree:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Datree
    uses: HariSekhon/GitHub-Actions/.github/workflows/datree.yaml@master
    with:
      path: ${{ github.event.inputs.path || '**.y*ml' }}
      cliArguments: ${{ github.event.inputs.args || '--only-k8s-files' }}
      isHelmChart: ${{ github.event.inputs.isHelmChart }}
      helmArguments: ${{ github.event.inputs.helmArguments }}
      isKustomization: ${{ github.event.inputs.isKustomization }}
      kustomizeArguments: ${{ github.event.inputs.kustomizeArguments }}
    secrets:
      DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
